# Generated by Django 5.0 on 2023-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ImageField(null=True, upload_to='person_profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password1', models.TextField(max_length=20)),
                ('password2', models.TextField(max_length=20)),
            ],
        ),
    ]
