# Generated by Django 5.0 on 2023-12-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=1000, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
