# Generated by Django 5.0 on 2023-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
