# Generated by Django 5.0 on 2023-12-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_purchase_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
    ]
