# Generated by Django 5.0.1 on 2024-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
