# Generated by Django 5.0.1 on 2024-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='funder',
            field=models.CharField(max_length=200),
        ),
    ]
