# Generated by Django 5.0.1 on 2024-02-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacementtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
