# Generated by Django 5.0.1 on 2024-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesReportDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
