# Generated by Django 5.0.1 on 2024-02-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0002_expensesreportdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpensesReportDescription',
            new_name='ExpensesCentralizerDescription',
        ),
    ]
