# Generated by Django 5.0.1 on 2024-02-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0002_alter_displacementtype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectScope',
            new_name='ProjectType',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_scope',
            new_name='project_type',
        ),
    ]
