# Generated by Django 5.0.1 on 2024-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0003_rename_expensesreportdescription_expensescentralizerdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpensesCentralizerDescription',
            new_name='ExpensesCentralizerDetails',
        ),
    ]
