# Generated by Django 5.0.1 on 2024-02-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbudget', '0004_rename_expensescentralizerdescription_expensescentralizerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensescentralizerdetails',
            old_name='description',
            new_name='details',
        ),
    ]
