name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Înlocuiește cu numele branch-ului tău principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build and deploy
      run: |
        # Adaugă pașii necesari pentru a construi proiectul tău, dacă este cazul
        # Pentru un proiect static simplu:
        mkdir -p build
        cp -r * build

      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
